/* Calculon © 2013 David Given
 * This code is made available under the terms of the Simplified BSD License.
 * Please see the COPYING file for the full license text.
 */

#ifndef CALCULON_H
#error "Don't include this, include calculon.h instead."
#endif

REAL1(acos)
REAL1(acosh)
REAL1(asin)
REAL1(asinh)
REAL1(atan)
REAL2(atan2)
REAL1(atanh)
REAL1(cbrt)
REAL1(ceil)
REAL2(copysign)
REAL1(cos)
REAL1(cosh)
REAL1(erf)
REAL1(erfc)
REAL1(exp)
REAL1(exp2)
REAL1(expm1)
REAL1(fabs)
REAL2(fdim)
REAL1(floor)
REAL3(fma)
REAL2(fmax)
REAL2(fmin)
REAL2(fmod)
REAL2(hypot)
REAL1(j0)
REAL1(j1)
REAL1(lgamma)
REAL1(log)
REAL1(log10)
REAL1(log1p)
REAL1(log2)
REAL1(logb)
REAL1(nearbyint)
REAL2(pow)
REAL2(remainder)
REAL1(rint)
REAL1(round)
REAL1(sin)
REAL1(sinh)
REAL1(sqrt)
REAL1(tan)
REAL1(tgamma)
REAL1(trunc)
REAL1(y0)
REAL1(y1)
